### ISSUE TITLE
zato.security.jwt.log-in service in zato 3.0 always return "Invalid username or password"

### ISSUE THREAD

**Issue by luhaihua** [zatosource/zato#1082]
Is it an known issue in 3.0?  The default password has been updated definitely:)

Found the implementation has been changed in 3.1.

**Comment by dsuch** [comment]
Hello @luhaihua,

I am closing this ticket because Zato 3.0 no longer receives any free  support.

If you have any issues with the currently supported version (3.1), please open a new ticket, including a detailed description of the situation along with sreenshots, code and log files confirming it.

Regards.
