### ISSUE TITLE
How to get file obj like in Django (request.FILES.get())

### ISSUE THREAD

**Issue by everraise** [zatosource/zato#1132]
I have seen your bolg about the REST programming example request and response section, there is a question, I want to know how to get a file object like the request.files.get () method in Django.

**Comment by everraise** [comment]
Looking forward to your reply！

**Comment by dsuch** [comment]
Hello @everraise,

I am not sure what you would like to achieve - are you uploading files to Zato from a web form? Please explain fuller what you are doing.

Thanks.

**Comment by everraise** [comment]
What I mean is that I want to publish a service on the REST channel to get the FILES object of the front-end application

**Comment by everraise** [comment]
Looking forward to your reply!

**Comment by dsuch** [comment]
Please reread my questions - I already know that you want to "get the FILES object" but I have no idea what it means in terms of HTTP, REST and frontend or server programming.

**Comment by everraise** [comment]
I have hot deployed a service on Zato and then published it to the REST channel. I have written a service that wants to get the file object of a third party application, but I don't know how to get it.

**Comment by dsuch** [comment]
Please understand that I have no idea what "getting the file object" means. This is some non-standard terminology which you use and I just do not know what it is.

There is no such thing as "getting the file object" in HTTP programming and I honestly do not know what you mean. Please describe what it is. Please do not repeat again that you need to "get the file object" because it does not tell me anything.

**Comment by everraise** [comment]
How to implement request.files.get () in the ZATO published service like in Django

**Comment by dsuch** [comment]
Alright, when time permits, I will check what request.files.get() means in Django and let you know how to do it in Zato too.
