### ISSUE TITLE
License clarifications

### ISSUE THREAD

**Issue by jpoa** [zatosource/zato#1192]
Greetings,

Wondering why LGPL was chosen over a BSD license for instance. For me its a bit confusing how LGPL is interpreted in the scope of Python (and other have the same questions, as per https://github.com/koalalorenzo/python-digitalocean/issues/224 for instance).

Any comments on this?

(and eventually if something like BSD can be considered)

Nonetheless thanks for a very nice piece of software.

**Comment by dsuch** [comment]
Hello @jpoa,

if your organization has any questions regarding the license of the software, please advise your lawyers to contact legal-at-zato.io.

Thank you.

**Comment by jpoa** [comment]
Well, not the type of answer I was expecting and definitely don't see the point of involving lawyers into this, was mostly asking out of curiosity (if anything this makes me raise my eyebrows). Thanks for taking the time to answer though.

**Comment by dsuch** [comment]
Hello again,

please look at it from my perspective.

An anonymous person, who I can identify only as "jpoa", asks a legal question without providing any background or context.

I have no idea what this stems from, why it is brought forward, what the intention is, and why it matters at all, not to mention that GitHub is a place to discuss software, not legal matters.

In such circumstances, I can only repeat the same recommendation as previously.

**Comment by jpoa** [comment]
Greetings @dsuch,

Within GitHub there are several such discussions in several projects, it is an important matter and one would think it is pretty much related to software not necessarily a legal matter, in my opinion that is precisely the idea of such licenses, to avoid legal interactions with lawyers et all. For your reference in case of curiosity: [Racket](https://github.com/racket/racket/issues/1570), [OpenCV](https://github.com/opencv/opencv-python/issues/615), [Prophet](https://github.com/facebook/prophet/issues/2087), [Neovim](https://github.com/neovim/neovim/issues/9933) and [flannel](https://github.com/flannel-io/flannel/issues/1350) are having such discussions, amongst others.

One would be inclined to say you would think the same since it is literally in the first sentence of your (?) description of the project, quote:

"The next generation ESB and application server written in Python and released under a commercial-friendly LGPL license."

This is what this stems from. Myself and several others dealing with software matters have open discussions about the commercial friendliness of licenses, and being LGPL of particular subjective interpretation I simply decided to ask. It is brought forward based on the aforementioned several discussions that one encounters repeatedly online and offline, including feedback and reactions such as the ones found in this thread. The intention is simply to have clarity, and as to why it matters, well, if this is not clear by now then there is little left to add from my part. Asking for details regarding the very first sentence used to describe the project is met with an invitation to arrange a meeting with lawyers.

From my side I can understand your reservations, probably you already had bad experiences in the past or there is more to it than I am able to comprehend, things are always easier when seen from outside and without context, as you mentioned already. My bad.

I did search for answers in the forums and past issues before opening a new one, thought that the community would benefit from an open discussion (even if for curiosity) and, at least for me, Twitter and LinkedIn are not the place where most developers gather so it made sense for me to do it here. Was not aware that there was a policy in the project against this.

@dsuch, I admire your work, your effort and your technical capabilities and insights, have done so for the last couple of years and will remain to do so.

Opened this issue with no ill intention, looking for answers knowing that there is no definitive right or wrong and that everyone has different points of views, the right to do so and that at the end we can only hope to come out of a discussion with new perspectives. I leave with more questions, which is not necessarily a bad thing.

It is your project and as such I will respect your guidelines and follow your recommendation, could never be otherwise. Once again I thank you for taking the time to answer me back, this issue is resolved for me.

**Comment by dsuch** [comment]
Hello again @jpoa,

thank you for providing all the details - the situation is much clearer to me.

I consider GitHub a place to open tickets to do with functionality, feature and various capabilities of this software. Essentially, a support site for working programmers that have exhausted other means of discussion.

I also recognize that you and other people may be interested in the answer to the question of "Why Zato uses this particular license" and now that I understand the background of your question, I will be happy to answer it, although please note that I will not be able to follow the links that you shared with me or follow the discussion elsewhere.

To understand why Zato uses this license, you need to understand that there are several parties interested in the usage of the software:

1. Companies and other entities using it directly
2. Independent software vendors
3. [Zato Source](https://zato.io) (company creating Zato)
4. Hobby programmers, casual lurkers and accidental users

* **Group 1**
  * Organizations from this group want to use the software for their own internal purposes and the license allows to do it. They can build any kind of solutions with it and this is what they do with Zato.

* **Group 2**
  * ISVs creating solutions for other organizations, typically for Group 1, consider Zato a capability in their overall portfolio.
  * They do not always want to share the source code of final solutions with their clients, nor are the clients always interested in having access to the source code, and the license allows to maintain this dynamic.
  * However, some of the Group 2's clients may be interested in having a certainty that ISVs actually use the same software that Zato Source produced. That is, the clients may want to be certain that ISVs do not alter the source code of Zato. For instance, some clients will want to have a list of specific versions (such as git commit IDs) that the solutions built for them are based on. Either such a commit ID must have been produced by Zato Source or the clients must be given access to the modification by ISVs so as to have complete access to the entire software stack. The license allows the clients to require that.

* **Group 3**
  * Zato Source builds solutions for and works with both Group 1 and Group 2. We are a supplier playing an active part in this supply chain and it is in our interest to ensure that the needs of both groups are satisfied.

* **Group 4**
  * These are simply people that accidentally stumble upon the software on GitHub and use some parts of it, educate themselves on it or otherwise are curious readers of the source code.

In short, this license is fair to everyone interested:

* If you want to build a solution for your own needs, you are welcome.
* If you build solutions for other people, the results of your work may be open-source or not, depending on what you or your clients require.
* If you are a client, you can be certain that, should you need it, you will be able to have full access to the solution that is built for you.
* It is fair to us (Zato Source) because it lets us work with clients and ISVs producing both proprietary and open-source solutions.
* If you are a casual programmer that needs to have a look at our source code, feel free to have a look at it.

However, there is one group of people that this license does not accommodate - these are companies that consider open-source software a reservoir of free labour.

That is, companies who are not our clients, who do not want to contribute back anything to us, who do not want to give access to the source code of their solutions to their own clients and who simply think that open source is good because it usually does not incur license fees.

These are typically companies that consider access to open source software their inborn right and who will typically have very weak understanding of what a supply chain is, how to work with suppliers or how to maintain a long-term relationship. It is not in our interest to fulfil the needs of such users.

To summarize - there are various parties interested in the software and the license is good for every one of them.

It is not the only such license, other similar ones could be AGPL, SSPL or MPL. Currently, Zato uses LGPL and it fulfils all the requirements.
