### ISSUE TITLE
Add API tests for zato.security.basic-auth.* services

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#332]

**Comment by ivaano** [comment]
I think we should keep all the scenarios that belong to basic-auth in one feature file, because if we split them up we will be pretty much duplicating each feature file, unless we do custom steps, for example:

lets assume we are going to split basic_auth_create and basic_auth_delete, ideally we just put:

- 1 scenario in create feature.
- 1 scenario in change_password feature.
- 3 scenarios in http_cannel (create, test valid, test invalid) feature (to test create service).
- 1 scenario in delete feature.

The first problem would be the test dependency, as we will need to specify the order of how tests are run, we can rename the feature files to 1_zato_security_basic_auth_create.feature, 2_zato_security_basic_auth_change_password.feature and so on, or we can pass the order as a behave option, but it will make automated testing a bit more problematic.

Second problem is with the feature context, we will need to extend the `before_feature` context for each feature we create to test if previous feature was successful, and add the results to the context so subsequent features can use the values.

Right now the `zato_security_basic_auth.feature` meets all the criteria with the exception of 

> For each service listed below add a separate .feature file
