### ISSUE TITLE
new connection type for SAP

### ISSUE THREAD

**Issue by opensourcechris** [zatosource/zato#385]
Since we have Odoo support why not support SAP as well: python sap rfc library, https://github.com/SAP/PyRFC.

**Comment by dsuch** [comment]
Hi @chrisgogreen - yes, we're definitely going to have it added.

I am to some point waiting until we have plug-ins ready - around July-October this year if everything goes according to the plans:

https://mailman-mail5.webfaction.com/pipermail/zato-discuss/2015-January/000796.html

It will then only a matter of authoring a plug-in instead of developing a client in code.

A SAP friend of mine recommended Mini SAP to test the support against last time I asked about it. 

Perhaps you'd like to add something else as well?

http://www.sdn.sap.com/irj/sdn/index?rid=/library/uuid/90e28332-ac79-2e10-b5a0-d628ec94edbf

**Comment by dsuch** [comment]
Done in #829.
