### ISSUE TITLE
Services sending XML always require input parameters

### ISSUE THREAD

**Issue by Cito** [zatosource/zato#389]
Take for example the following service that only produces output and has not input:

```
class OutputOnlyService(Service):

    class SimpleIO:
        output_required = ('output',)

    def handle(self):
        self.response.payload.output = "Hello World!"
```

When I use this in a HTTP plain channel set to JSON, everything works fine. But when I set the channel to XML, I get an XMLSyntaxError. It seems Zato always tries to parse the incoming XML, even if there is no input.

**Comment by dsuch** [comment]
Hi @Cito - how do you invoke such a channel, exactly?

**Comment by Cito** [comment]
Just sent a request:

    curl http://localhost:11223/test-service

When I set the data format of the channel to JSON, it works. When I set it to XML, I get that error because Zato tries to parse an empty string as XML. There are certainly some use cases where you want XML output, like e.g. the current time, without any input. It does not matter whether you send via GET or POST, e.g.

    curl http://localhost:11223/test-service -d ""

It works only when you send an empty XML element:

    curl http://localhost:11223/test-service -d "<xml/>"

**Comment by dsuch** [comment]
Ok, @Cito - but how to deal with it really? An empty string is not a valid XML document so it is expected that it cannot be parsed as such. This is unlike JSON which can accept empty strings or null values.

Right now the only thing that springs to mind for 2.1 is:

* Leave the current behaviour as is
* Add a flag to server.conf that will dictate how to proceed upon receiving an empty string/None as XML

I'd rather not change the behaviour because it may mask issues in client applications.

However, I can see where you're coming from hence the flag in server.conf.

What would you say?

**Comment by dsuch** [comment]
> I'd rather not change the behaviour because it may mask issues in client applications.

Let me clarify - I'd rather not change the default behaviour.

**Comment by Cito** [comment]
Naively I would suggest, if `input_required` and `input_optional` are both empty, then don't parse the input as XML since the service obviously doesn't expect any input, and set request.input to None.

**Comment by dsuch** [comment]
Right, this is good, but if a service doesn't use SimpleIO?

**Comment by Cito** [comment]
If SimpleIO is not used and there is no input, then you could also skip the parsing and simply set request.input and request.payload to None. If the service will try to access the input, then it will get an error because it's None. So errors would be detected anyway.

**Comment by davinirjr** [comment]
+1
