### ISSUE TITLE
Add Oauth and Oauth2 as one of the standard auth methods

### ISSUE THREAD

**Issue by vabue** [zatosource/zato#484]
Oauth is a popular methods of authorization in the modern web. It is very popular in single sign-on systems - https://en.wikipedia.org/wiki/List_of_OAuth_providers

There are some popular libraries in Python to work with this protocol:
- [oauthlib](https://github.com/idan/oauthlib)
- [oauth2lib](https://github.com/NateFerrero/oauth2lib)

**Comment by vabue** [comment]
Also there is convenient https://github.com/requests/requests-oauthlib

**Comment by sebbean** [comment]
@dsuch about to implement a connection with Spree Platform's OAuth implementation
https://api.spreecommerce.org/docs/api-v2/d014178e4ee93-create-or-refresh-a-token

Looks like OAuth2?
Can you confirm this is not a built in feature of Zato (i'm seeing oauth in the menus but no clear way to implement)

I'll look to approach the token storage in the service itself and use the key value store

**Comment by dsuch** [comment]
Hello @sebbean,

what you linked to looks like an endpoint that returns a token which is then to be used as the "Bearer" header in subsequent interactions with this application.

To send HTTP headers, one uses code as in the examples here: https://zato.io/en/docs/3.2/dev/rest/outconns.html

Since this is not the first time it happens from your end, I will also add that I expect basic manners from anyone requesting support. This includes matters such as "Hello", "Good day", "Thank you" or using proper grammar if you are a native English speaker.

Regards.

**Comment by yhorndt** [comment]
Hi @dsuch,
I see that the Salesforce connector will do basically what is asked.
I specifically run into it now with SuiteCrm/sugarcrm. I assume that under the water it will refresh the token if not valid anymore?

Ofcourse this is possible to do by coding the header into the request, but doesn't this defeat the purpose of the esb configuration dashboard?
Now I have a service, which I call in python, retrieve token (in body), add this as a header to another request (for another service (post for retrieving token, get for getting data), check when I get a response if status is 200, if 401 request another token.

I see in the documentation the reference to oauth, but not in the security tab in my 'most recent' quickstart docker container.

I hope I've explained myself well.
