### ISSUE TITLE
ValueError at /zato/http-soap/

### ISSUE THREAD

**Issue by hend10** [zatosource/zato#579]
I get a ValueError(version1.1) when i  try "Connections" -> "Channels" -> "Plain HTTP" in the option show channels.

this is th error exception displayed http://pastebin.com/qceLEhaS

I need a fix quickly.

**Comment by walidjlidi** [comment]
I got the same error version 1.1 . @dsuch is there any hotfixe to fix this problem.

**Comment by dsuch** [comment]
Hello,

my apologies but GitHub has only now sent in a notification that this ticket was opened two days ago.

I understand that this is a pressing need @hend10 @walidjlidi but this is free support over GitHub.

If you need to have a fix quickly please send an email to info@zato.io and I will be happy to discuss with you terms of commercial support that includes guaranteed reaction and response times.

Thanks.

**Comment by walidjlidi** [comment]
Hi ,

Thanks a lot for your response. I'm a student in a training and my mission is to prepare a prototype application. I'm sure if everything work well the company will recruit me. As you know company don't pay for half solution. They need to see something work after we discuss commercial support. I'm pressed by the deadline that's why i asked the help in the week-end day.

**Comment by dsuch** [comment]
Hi there,

sure thing @walidjlidi - I am not sure if you and @hend10 are part of the same team but in my previous comment I was confirming that if time is of importance then priority support is available outside of GitHub.

As for the original question - can you please that yours and that of @walidjlidi's questions is the same?

If so and if this is a new solution then you should definitely use 2.0 instead of 1.1.

Thanks.

**Comment by walidjlidi** [comment]
Thanks again for your response. I will install the version 2.0.

**Comment by dsuch** [comment]
I believe this can be closed - please reopen any time if needed. Thanks.
