### ISSUE TITLE
How do I install zato framework from source ?

### ISSUE THREAD

**Issue by codepython** [zatosource/zato#668]
Is there any document for this relevent topic ?

**Comment by dsuch** [comment]
Hi @codepython,

thanks for asking - I have just added the instructions here:

https://zato.io/docs/admin/guide/install/source.html

Regards.

**Comment by codepython** [comment]
OK ,thanks.
but why does it not include install instruction for macos ?

**Comment by dsuch** [comment]
> but why does it not include install instruction for macos ?

Because as things stand today, OS X is not one of systems that Zato runs natively on.

https://zato.io/docs/admin/guide/install/index.html

It is planned to port Zato to OS X but this is not something that will be done soon now unless there is a sponsor for the job. Please feel free to contact me on dsuch@zato.io if you'd like to discuss it. Thanks!
