### ISSUE TITLE
Stats jobs

### ISSUE THREAD

**Issue by triplegrr** [zatosource/zato#799]
Looks like there is something missing with `v3` when it comes to stats. 

After inspecting the DB in v2 these rows are visible.

```
1|zato.stats.process-raw-times|1|interval_based|2017-11-06 08:15:27.726252|max_batch_size=99999|1|367
2|zato.stats.aggregate-by-minute|1|interval_based|2017-11-06 08:15:27.874120||1|364
3|zato.stats.aggregate-by-hour|1|interval_based|2017-11-06 08:15:28.011056||1|363
4|zato.stats.aggregate-by-day|1|interval_based|2017-11-06 08:15:28.212909||1|362
5|zato.stats.aggregate-by-month|1|interval_based|2017-11-06 08:15:28.333042||1|365
6|zato.stats.summary.create-summary-by-day|1|interval_based|2017-11-06 08:15:28.484466||1|370
7|zato.stats.summary.create-summary-by-week|1|interval_based|2017-11-06 08:15:28.662463||1|372
8|zato.stats.summary.create-summary-by-month|1|interval_based|2017-11-06 08:15:28.797746||1|371
9|zato.stats.summary.create-summary-by-year|1|interval_based|2017-11-06 08:15:28.994618||1|373
10|zato.outgoing.sql.auto-ping|1|interval_based|2017-11-06 08:15:29.114542||1|325

```
However. In v3. the `job` table is completely empty. 

This is causing a 5XX error on http://localhost:8183/zato/stats/settings/?cluster=1

**Comment by dsuch** [comment]
Hi @triplegrr,

this is caused by the fact that the scheduler is not running - in 3.0 it needs to be managed separately, including zato start/stop commands.

Once you start it, it will populate the table with relevant objects. Can you do it?

I will keep this ticket open because there should not be a 500 error anyway, instead there simply should be no jobs.

Thanks.

**Comment by dsuch** [comment]
Thanks @triplegrr - since commit dac68c3a23453f0b880486cb0ad27df8127e490d we now display a warning message instead of HTTP 500.
