### ISSUE TITLE
Use zato.io with rancher.com

### ISSUE THREAD

**Issue by lexapi** [zatosource/zato#809]
Using the rancher.com, we can control the scalability dynamically, but in this case the built-in balancer will not see the new raised containers.
It is safe? Maybe you can somehow turn off the built-in LB ?

If go another way and simply to clone the server containers - they are not visible in the interface, although I can manually add it to the config LB (and he is green in zato-lb-stats). Which scenario is better to use?

**Comment by dsuch** [comment]
Hello @lexapi,

I'm not sure about https://rancher.com - I have not seen it before so I'm not 100% clear how it works and I cannot immediately comment on how to integrate it with Zato.

I can, however, confirm that you can use any load-balancer you want in front of Zato servers, you do not need to use the built-in one.

In that case all the LB-relevant screens in web-admin will not work because they assume our own LB is running. But other than that, yes, you can use any other LB.

How do other servers integrate with Rancher? What is it that Rancher expects of servers that are under its control? Any Dockerfile simply? Or did you have to customize our default Dockerfiles?

Regards.

**Comment by lexapi** [comment]
Rancher is a container manager, and he doesn't care what to run - Dockerfile or Docker-compose files
It is not presented any requirements to run service, we can write a custom health-check for each service

How zato-LB check servers -  Is he alive or dead?? 
To what I understand, LB XML-RPC agent somehow involved in this?

**Comment by dsuch** [comment]
> How zato-LB check servers - Is he alive or dead??

Zato uses an embedded HAProxy instance as its LB. The configuration is kept in a given LB's zato.config file. Please refer to HAProxy's documentation for details.

>  To what I understand, LB XML-RPC agent somehow involved in this?

The agent is used only by web-admin to send remote commands to LB. It is not involved in health-checks.

>  "LB HTTP health-check" used to monitor the LB itself ?

Yes, this is correct.

Additionally, each Zato server exposes a URL path of /zato/ping which you can invoke to find out if a given server replies with 200 OK or not.

**Comment by dsuch** [comment]
I think this answers all the questions and I'm closing the ticket.
