### ISSUE TITLE
Can not start Zato

### ISSUE THREAD

**Issue by sherry0429** [zatosource/zato#816]
first i lead all step in here：
https://zato.io/docs/admin/guide/install/rhel.html

and then i make redis and start it，install pysqlite by pip， install sqlite sqlite-devel by yum。

and i closed firewall

now run a cmd like ‘zato quickstart create ~/env/qs-1 sqlite {myip} 6379 --kvdb_password '' --verbose’

it shows：

[1/8] Certificate authority created
[2/8] ODB schema created
[3/8] ODB initial data created
[4/8] server1 created
[5/8] server2 created
[6/8] Load-balancer created
[pty@localhost ~]$ 

seem like step 7 and 8 not started, any one can help me ?

my system info :

rhel 6.2 (virtual machine in vmware, 2 core, 20GB, and 4G memory)
python 2.7.13

thanks.

**Comment by dsuch** [comment]
Hi @sherry0429 - is that RHEL 6 a 32-bit or a 64-bit system?

**Comment by sherry0429** [comment]
@dsuch it's RHEL 6.2 64-bit system.
i install it by rhel-server-6.2-x86_64-dvd.iso

and my virtual machine softeware is VMWare.

i want to study source code, but i have no idea where to start, it seem like some compoments, i don't know where to start, can you tell me the zato's Program entrance？thanks

**Comment by dsuch** [comment]
Hi @sherry0429 - thanks for that info, there was another ticket that seems related to RHEL too and I plan to see to it over the weekend.

As for the source code, what part do you have interest in, particularly? Zato is over 100k lines of code, it would be great if you could explain your needs and pursuits fuller.

Regards.

**Comment by sherry0429** [comment]
@dsuch  first, i do the all same operation on CentOS-6.9-x86_64-minimal.iso (also virtual machine in vmware),  this info maybe get some help, i think maybe it's rhel system's problem.

all i want to study is that:
write code, and bind it by web, call it and it's function run. all this can do with a template.

i want to make a system like this:
services is dynamic, i can enable/disable it, and i control it's life cycle like start, loop, destroy.
service have some steps and it have fileinput/fileoutput, services between them maybe have some delay. like serviceA produce data B, service C use B produce data D.

although zato can do this but our client use windowsXP or rhel lower than 6.2 ( even 4.1...），so i have to make wheel for them.

now our system can do what i said, but service is many many many..., I need a framework to standardize its development, and make it's development templated.

Can you provide some advice? thank you.

**Comment by dsuch** [comment]
Hi @sherry0429,

I'd like to ask you not to use RHEL 6 for the time being - there are issues that we will be working on but they require extensive changes to our build infrastructure first, related to the fact that RHEL 6 uses Python 2.6 by default and pip soon will stop to support this Python version. We will need several weeks at least to implement all the changes because they need to be applied to all the systems that we support, not only to RHEL 6.

As a side note - please use the latest sub-release of a given OS. In your case, it would be RHEL 6.9. It's not related directly to this ticket but I'm adding it as a general note that we cannot support old sub-releases unsupported by their vendors.

Your list of requirements is understood and there is no difficulty with achieving it with Zato. If you can, please, install on Ubuntu 16.04 64-bit and everything will be fine.

Regards.

**Comment by sherry0429** [comment]
Hi @dsuch 
I think you don't need fix this issue in RHEL old version, because it's version is too old to develop, i understand this, but our client's machine, system and other, we can not change, they have not 'root' access, so i can't tell them 'update your system and we will support you', i only do is 'ok, i will make a program run on this sytem'....

that's like thery are father,,

first i make this issue is want to use zato but then i find it's to hard, our client is old man, old thinking, and hard to changed, so i have to make a wheel by our own.

so can you tell me where to study my interested in zato ? like service templated and standardize develop. if here are some reason you can not do that ( some protect thinking ), i can understand it.

thanks, i have not other question on this, you can close this issue. zato is great, but i am very sad about that i can not use it on my old clients ooooold machine    = 。=

**Comment by aek** [comment]
@sherry0429 the same is discussed here:
https://forum.zato.io/t/odb-ha-reconnection-issue-affecting-scheduled-services/1312/18?u=aekroft
There is nothing that prevents you to manually install it without using the OS package. In fact, there is a doc entry covering the install from sources
https://zato.io/docs/admin/guide/install/source.html
And in the forum link above there are 2 ways to get RHEL 6 with python 2.7 who is the main cause that prevents Zato to support RHEL 6 due that it ships with the old python 2.6

**Comment by sherry0429** [comment]
@dsuch  ok i get it, thanks,
 but actually, even if i finish that, client's system maybe rhel 4.1/4.2 or windows XP ... , i will think about this, thanks a lot.

**Comment by dsuch** [comment]
Hi @sherry0429 - what @aek said is correct and you can certainly follow this advice.

Let me only add that:

* The fact that you have issues with RHEL 6 is something to fix on our end, there is no ETA for it yet.
* Zato will not run on RHEL older than 6 so 4.1/4.2 are ruled out.
* It will also not run on Windows - we plan to have a version for Windows but only for development purposes, i.e. so that developers can use it in their work with production on Linux.
* Before we have a version for Windows we will have a version for OS X first, it's easier to port Zato to a UNIX system first - feel free to subscribe to ticket #818 if you are interested in it.

**Comment by sherry0429** [comment]
@dsuch  ok, actually i have device make our own wheel, just a small service framework core in here, https://github.com/sherry0429/SOAForPython,  many thanks for your advice, have a nice day o(*￣︶￣*)o
