### ISSUE TITLE
Investigate alternative Odoo clients / add out_odoo.client_type

### ISSUE THREAD

**Issue by dsuch** [zatosource/zato#848]
This is in reference to comments by @jpoa in #833.

The idea is first to add a new field to out_odoo model by the name of 'client_type'.

By default it will read 'openerp-client-lib' but if needed and if alternative clients are deemed satisfactory, more client types can be added.

Since the new field will be already in place, existing Zato installations will be able to make use of other clients without a need for SQL migrations.

At the same time, existing codebase will not have to migrate, it will be able to use the current client for as long as required.

**Comment by dsuch** [comment]
Column out_odoo.client_type was added in commit 11f812c1b2fa926cefd8ee8c166c2b692194019b so now it is a matter of investigation of the other Odoo clients.

**Comment by jpoa** [comment]
Great, thanks, I will have a go at it.

**Comment by jpoa** [comment]
Greetings,

I am trying to install erppeek in Zato, from what I could find Zato as its own python and pip, so I tried to install as follows:

`root@6654850fe63c:/opt/zato/env/qs-1# /opt/zato/3.0/code/bin/pip install erppeek   `
`Requirement already satisfied: erppeek in /opt/zato/3.0/code/lib/python2.7/site-packages (1.6.3)    `
`watchdog 0.8.3 has requirement argh>=0.24.1, but you'll have argh 0.23.2 which is incompatible.   `
`sphinx 1.7.5 has requirement Pygments>=2.0, but you'll have pygments 1.5 which is incompatible.   `
`zato-apitest 1.11 has requirement base32-crockford==0.2.0, but you'll have base32-crockford 0.3.0 which is incompatible.   `
`zato-apitest 1.11 has requirement cassandra-driver==2.1.1, but you'll have cassandra-driver 3.0.0 which is incompatible.   `
`zato-apitest 1.11 has requirement click==4.0, but you'll have click 1.1 which is incompatible.   `
`zato-apitest 1.11 has requirement configobj==5.0.5, but you'll have configobj 5.0.6 which is incompatible.   `
`zato-apitest 1.11 has requirement lxml==3.3.5, but you'll have lxml 3.7.3 which is incompatible.   `
`zato-apitest 1.11 has requirement parse==1.6.4, but you'll have parse 1.6.6 which is incompatible.   `
`zato-apitest 1.11 has requirement psycopg2==2.5.3, but you'll have psycopg2 2.7.4 which is incompatible.   `
`zato-apitest 1.11 has requirement python-dateutil==2.2, but you'll have python-dateutil 2.6.0 which is incompatible.   `
`zato-apitest 1.11 has requirement requests==2.3.0, but you'll have requests 2.19.0 which is incompatible.   `
`zato-apitest 1.11 has requirement six==1.6.1, but you'll have six 1.10.0 which is incompatible.   `
`zato-apitest 1.11 has requirement sqlalchemy==0.9.7, but you'll have sqlalchemy 1.2.8 which is incompatible.   `
`root@6654850fe63c:/opt/zato/env/qs-1#`

Is this the wrong approach at all? If so, what would be the right one?

If it is, then it seems there are some incompatibilities due to old libraries, is there any chance of bumping them up without breaking Zato? I am willing to look into it, just would like to avoid opening a pandora box or going completely the wrong way.

The objective is in the end to support more libraries in the services that I define, one other case would be for instance this library that I want to use in a service: https://github.com/python-gitlab/python-gitlab

What is the best approach? Import it inside the service or define a new connector?

**Comment by dsuch** [comment]
Hello @jpoa,

right now, the best way is to import them in your services - there is no user-visible API to define new connectors and the overall idea is to have plugins of highly declarative nature rather than exposure of connectors to users.

These plugins will in turn use the connector APIs but without making the internals accessible to users which will let the internals be changed if needed without breaking anything for users.

But it won't happen in the next few months (summer time in Northern hemisphere) so at this very point your best course of action are direct imports.
