### ISSUE TITLE
Self.outgoing.amqp.send returning None ||New feature

### ISSUE THREAD

**Issue by saibhargavkatragadda08** [zatosource/zato#889]
The self.outgoing.amqp.send() of AMQP is returning None as its output even when the items are pushed on to the queue.Add the feature to return success response if the items are pushed on to the queue.

**Comment by dsuch** [comment]
Hello @saibhargavkatragadda08 - I investigated the matter and unfortunately I need to close the ticket.

The reason is that our underlying library (kombu) does not support AMQP confirms nor the parameter called 'mandatory' that the AMQP protocol itself supports.

I could not get it to work reliably with kombu so I am compelled to close it until there is a sponsor to cover this work under a commercial agreement. If you are interested, please contact me directly on dsuch at zato.io.
