### ISSUE TITLE
Add possibility to use converters in channel route definitions

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#893]
REST channels could have the possibility to add a converter to arguments. This converter makes it possible to define the type of the parameter. See: https://forum.zato.io/t/path-precedence-for-http-rest-channels-in-zato-3/1677/7

Something like: `/api/resource/<converter:identifier>`

Where converter can be str, int, slug, uuid or path (like in Django)
Or, like Flask has: string, int, float, path and uuid.

For Django, the default situation (without a converter) is to match '/' as part of the identifier, for Flask, the '/' is default excluded from an identifier match.

To avoid problems with current Zato instances, this feature should be explicitly enabled.

**Comment by dsuch** [comment]
Slash matching in URL paths is done but I will keep the ticket open to keep the work on the datatypes in URL paths under it. Thanks again for the suggestion @jjmurre.

**Comment by dsuch** [comment]
I have had a look at what Flask does and, given that we already have slash character matching, I think that the only other useful converter would be **int**, do you not think @jjmurre?

Other than that, what we have today can be said to represent a **string** converter, so that does not have to be implemented.

But other than that, it really looks like only int is something to be added?

**Comment by jjmurre** [comment]
Yes, I think int vs string distinctions is enough.

**Comment by jjmurre** [comment]
Actually, the biggest issue was the trailings slash, and that has been fixed already.
Adding an int converter would be nice, because then the distictinction between /resource/<int:resource_id> and /resource/<some string identifier> is clear. I don't think this is a very urgent issue.
