### ISSUE TITLE
Web-admin strarting not as daemon

### ISSUE THREAD

**Issue by crsde** [zatosource/zato#944]
Hello, looks like after last update, web-admin behave not like before. 
Now issuing `zato start web-admin`
starts web ui so that log outputs to stdout.
```
zato@esb-server:~/kbus$ Installed 1 object(s) from 1 fixture(s)
Performing system checks...

System check identified no issues (0 silenced).
April 12, 2019 - 06:03:08
Django version 1.9.7, using settings u'zato.admin.settings'
Starting development server at http://0.0.0.0:8183/
Quit the server with CONTROL-C.

```
And web-admin dies once ssh session is closed...

**Comment by dsuch** [comment]
Can you tell me what your Zato version is?

**Comment by crsde** [comment]
Hello,
`Zato` 3.0.0+rev.f5dbf26b

**Comment by dsuch** [comment]
Just so that we talk about the same situation - when I run 'zato start /path/to/web-admin' I see that it starts in background as a deamon but, additionally, it logs data to stdout too. Is that what you are observing?

Also, can you tell me what the output of this command is?

cd /opt/zato/current
git log -1

It should be commit 3ba21a8079cd19fec1d48fc30d846903411767ca.

**Comment by crsde** [comment]
Hello i reverted to https://github.com/zatosource/zato/commit/79c2c29b51d3ef26100fb337c870bace63f0a032 before. 
But web-admin is still dies, once i exit ssh session.

**Comment by dsuch** [comment]
This was never reproduced on any system - closing the ticket, thanks @crsde.
